language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tak113/react-test -f ./client/Dockerfile.dev ./client

# test script
script:
  - docker run -e CI=true tak113/react-test npm run test -- --coverage

after_success:
  - docker build -t tak113/multi-client ./client
  - docker build -t tak113/multi-nginx ./nginx
  - docker build -t tak113/multi-server ./server
  - docker build -t tak113/worker ./worker
  # login to the dokcer CLI. DOCKER_ID and DOCKER_PASSWORD are in travis site (procet=>more options=>environment variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push tak113/multi-client
  - docker push tak113/multi-nginx
  - docker push tak113/multi-server
  - docker push tak113/multi-worker
